---

- name: "update apt packages"
  become: yes
  apt:  
    update_cache: yes

- name: "install python for Ansible."
  become: yes
  apt: name=python3 state=present

- name: "Enable the NodeSource repository"
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_12.x | -E bash -

- name: "install nodejs."
  become: yes
  apt: name=nodejs state=present

- name: "test npm"
  shell: which npm

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present