---

- name: "Enable the NodeSource repository"
  become: yes
  shell: echo "https://deb.nodesource.com/setup_12.x" | sudo tee -a /etc/apt/sources.list

- name: "update apt packages"
  become: yes
  apt:  
    update_cache: yes

- name: "install python for Ansible."
  become: yes
  apt: name=python3 state=present

- name: "install nodejs."
  become: yes
  apt: name=nodejs state=present

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present