---

- name: "update apt packages"
  become: yes
  apt:  
    update_cache: yes

- name: "install python for Ansible."
  become: yes
  apt: name=python3 state=present

- name: "install nodejs."
  become: yes
  apt: name=nodejs state=present

- name: "test npm"
  shell: which npm

- name: "install pm2."
  become: yes
  shell: /usr/bin/npm install pm2 -g